"""Localization data for weekdays, months, and UI text."""

WEEKDAYS = {
    "RU": ["понедельник", "вторник", "среда", "четверг", "пятница", "суббота", "воскресенье"],
    "UA": ["понеділок", "вівторок", "середа", "четвер", "п'ятниця", "субота", "неділя"],
    "EN": ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"],
}

MONTHS = {
    "RU": [
        "января", "февраля", "марта", "апреля", "мая", "июня",
        "июля", "августа", "сентября", "октября", "ноября", "декабря"
    ],
    "UA": [
        "січня", "лютого", "березня", "квітня", "травня", "червня",
        "липня", "серпня", "вересня", "жовтня", "листопада", "грудня"
    ],
    "EN": [
        "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE",
        "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"
    ],
}

TRANSLATIONS = {
    "EN": {
        "window_title": "N-Dot Clock",
        "edit_hint": "EDIT MODE: CLICK A CARD TO MODIFY",
        "add_card_slide_label": "ADD CARD",
        "add_menu_title": "ADD CARD",
        "weather_widget_button": "Weather Widget",
        "custom_card_button": "Custom Card",
        "youtube_button": "YouTube",
        "cancel_button": "Cancel",
        "clock_editor_title": "CLOCK SETTINGS",
        "brightness_label": "BRIGHTNESS:",
        "digits_label": "DIGITS:",
        "colon_label": "COLON:",
        "background_label": "BACKGROUND:",
        "auto_brightness_toggle": "Auto brightness",
        "save_button": "Save",
        "weather_editor_title": "WEATHER EDITOR",
        "show_temp": "Show Temperature",
        "show_icon": "Show Icon",
        "show_desc": "Show Description",
        "show_wind": "Show Wind",
        "custom_editor_title": "CUSTOM SLIDE EDITOR",
        "youtube_editor_title": "YOUTUBE EDITOR",
        "youtube_url_label": "YouTube URL:",
        "youtube_title_label": "Title:",
        "youtube_default_title": "YouTube",
        "ha_button": "Home Assistant",
        "ha_editor_title": "HOME ASSISTANT EDITOR",
        "ha_url_label": "Home Assistant URL:",
        "ha_title_label": "Title:",
        "ha_default_title": "Home Assistant",
        "loading_weather": "Loading weather...",
        "weather_wind": "Wind: {speed:.1f} m/s",
        "custom_default_text": "New custom card",
        "delete_button": "Delete",
        "delete_confirm_title": "Delete Card",
        "delete_confirm_message": "Are you sure you want to delete this card?",
        "yes_button": "Yes",
        "no_button": "No",
        "autostart_button": "Autostart",
        "autostart_enabled": "Autostart enabled",
        "autostart_disabled": "Autostart disabled",
        "autostart_error": "Failed to configure autostart",
        "webview_error": "Unable to load page. Check the address.",  # исправлено: сообщение об ошибке webview
        "auto_brightness_error_backend": "Auto brightness requires OpenCV and NumPy. Install the 'opencv-python' and 'numpy' packages.",
        "auto_brightness_error_camera": "Unable to open webcam for auto brightness.",
        "auto_brightness_error_capture": "Lost connection to the webcam during auto brightness.",
        "auto_brightness_error_generic": "Auto brightness stopped because of an unexpected error.",
    },
    "RU": {
        "window_title": "N-Dot Clock",
        "edit_hint": "РЕЖИМ РЕДАКТИРОВАНИЯ: НАЖМИТЕ НА КАРТУ ДЛЯ ИЗМЕНЕНИЯ",
        "add_card_slide_label": "ДОБАВИТЬ КАРТУ",
        "add_menu_title": "ДОБАВИТЬ КАРТУ",
        "weather_widget_button": "Виджет погоды",
        "custom_card_button": "Пользовательская карта",
        "youtube_button": "YouTube",
        "cancel_button": "Отмена",
        "clock_editor_title": "НАСТРОЙКА ЧАСОВ",
        "brightness_label": "ЯРКОСТЬ:",
        "digits_label": "ЦИФРЫ:",
        "colon_label": "ДВОЕТОЧИЕ:",
        "background_label": "ФОН:",
        "auto_brightness_toggle": "Автонастройка яркости",
        "save_button": "Сохранить",
        "weather_editor_title": "РЕДАКТОР ПОГОДЫ",
        "show_temp": "Показывать температуру",
        "show_icon": "Показывать значок",
        "show_desc": "Показывать описание",
        "show_wind": "Показывать ветер",
        "custom_editor_title": "РЕДАКТОР КАРТЫ",
        "youtube_editor_title": "РЕДАКТОР YOUTUBE",
        "youtube_url_label": "URL YouTube:",
        "youtube_title_label": "Название:",
        "youtube_default_title": "YouTube",
        "ha_button": "Home Assistant",
        "ha_editor_title": "РЕДАКТОР HOME ASSISTANT",
        "ha_url_label": "URL Home Assistant:",
        "ha_title_label": "Название:",
        "ha_default_title": "Home Assistant",
        "loading_weather": "Загрузка погоды...",
        "weather_wind": "Ветер: {speed:.1f} м/с",
        "custom_default_text": "Новая пользовательская карта",
        "delete_button": "Удалить",
        "delete_confirm_title": "Удалить карту",
        "delete_confirm_message": "Вы уверены, что хотите удалить эту карту?",
        "yes_button": "Да",
        "no_button": "Нет",
        "autostart_button": "Автозапуск",
        "autostart_enabled": "Автозапуск включен",
        "autostart_disabled": "Автозапуск выключен",
        "autostart_error": "Ошибка настройки автозапуска",
        "webview_error": "Не удалось загрузить страницу. Проверьте адрес.",  # исправлено: сообщение об ошибке webview
        "auto_brightness_error_backend": "Для автонастройки яркости нужны OpenCV и NumPy (пакеты opencv-python и numpy).",
        "auto_brightness_error_camera": "Не удалось получить доступ к веб-камере для автояркости.",
        "auto_brightness_error_capture": "Потеряно соединение с веб-камерой при автояркости.",
        "auto_brightness_error_generic": "Автонастройка яркости остановлена из-за ошибки.",
    },
    "UA": {
        "window_title": "N-Dot Clock",
        "edit_hint": "РЕЖИМ РЕДАГУВАННЯ: НАТИСНІТЬ НА КАРТКУ, ЩОБ ЗМІНИТИ",
        "add_card_slide_label": "ДОДАТИ КАРТКУ",
        "add_menu_title": "ДОДАТИ КАРТКУ",
        "weather_widget_button": "Віджет погоди",
        "custom_card_button": "Користувацька картка",
        "youtube_button": "YouTube",
        "cancel_button": "Скасувати",
        "clock_editor_title": "НАЛАШТУВАННЯ ГОДИННИКА",
        "brightness_label": "ЯСКРАВІСТЬ:",
        "digits_label": "ЦИФРИ:",
        "colon_label": "ДВОКРАПКА:",
        "background_label": "ТЛО:",
        "auto_brightness_toggle": "Автоналаштування яскравості",
        "save_button": "Зберегти",
        "weather_editor_title": "РЕДАКТОР ПОГОДИ",
        "show_temp": "Показувати температуру",
        "show_icon": "Показувати значок",
        "show_desc": "Показувати опис",
        "show_wind": "Показувати вітер",
        "custom_editor_title": "РЕДАКТОР КАРТКИ",
        "youtube_editor_title": "РЕДАКТОР YOUTUBE",
        "youtube_url_label": "URL YouTube:",
        "youtube_title_label": "Назва:",
        "youtube_default_title": "YouTube",
        "ha_button": "Home Assistant",
        "ha_editor_title": "РЕДАКТОР HOME ASSISTANT",
        "ha_url_label": "URL Home Assistant:",
        "ha_title_label": "Назва:",
        "ha_default_title": "Home Assistant",
        "loading_weather": "Завантаження погоди...",
        "weather_wind": "Вітер: {speed:.1f} м/с",
        "custom_default_text": "Нова користувацька картка",
        "delete_button": "Видалити",
        "delete_confirm_title": "Видалити картку",
        "delete_confirm_message": "Ви впевнені, що хочете видалити цю картку?",
        "yes_button": "Так",
        "no_button": "Ні",
        "autostart_button": "Автозапуск",
        "autostart_enabled": "Автозапуск увімкнено",
        "autostart_disabled": "Автозапуск вимкнено",
        "autostart_error": "Помилка налаштування автозапуску",
        "webview_error": "Не вдалося завантажити сторінку. Перевірте адресу.",  # исправлено: повідомлення про помилку webview
        "auto_brightness_error_backend": "Для автоналаштування яскравості потрібні OpenCV та NumPy (пакети opencv-python і numpy).",
        "auto_brightness_error_camera": "Не вдалося отримати доступ до вебкамери для автояскравості.",
        "auto_brightness_error_capture": "Втрачено з'єднання з вебкамерою під час автоналаштування яскравості.",
        "auto_brightness_error_generic": "Автоналаштування яскравості зупинено через помилку.",
    },
}
